# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_learn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='learn_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
    ]
