# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170126_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='learn_time',
        ),
    ]
