# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
